from setuptools import setup
import os
from glob import glob

package_name = 'sensor_fusion'

setup(
    name=package_name,
    version='0.1.0',
    packages=[package_name, package_name + '.test'],
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
        (os.path.join('share', package_name, 'launch'), glob('launch/*.launch.py')),
        (os.path.join('share', package_name, 'rviz'), glob('rviz/*.rviz')),
        (os.path.join('share', package_name, 'config'), glob('config/*.rviz')),
        (os.path.join('share', package_name, 'config'), glob('config/*.yaml')),
        (os.path.join('share', package_name, 'test'), glob('test/*.py')),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='Mostafa',
    maintainer_email='user@example.com',
    description='Sensor fusion package for LiDAR, radar, and IMU integration with trajectory planning',
    license='MIT',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            'fusion_costmap_creator = sensor_fusion.fusion_costmap_creator:main',
            'trajectory_planner = sensor_fusion.trajectory_planner:main',
            'imu_processor = sensor_fusion.imu_processor:main',
            'lidar_costmap_creator = sensor_fusion.lidar_costmap_creator:main',
            'lidar_listener_clusters_2 = sensor_fusion.lidar_listener_clusters_2:main',
            'lidar_listener_simple = sensor_fusion.lidar_listener_simple:main',
            'lidar_permanent_mapper = sensor_fusion.lidar_permanent_mapper:main',
            'lidar_realtime_mapper = sensor_fusion.lidar_realtime_mapper:main',
            'radar_costmap_creator = sensor_fusion.radar_costmap_creator:main',
            'radar_listener_clusters = sensor_fusion.radar_listener_clusters:main',
            'imu_listener = sensor_fusion.imu_listener:main',
            'imu_euler_visualizer = sensor_fusion.imu_euler_visualizer:main',
            'imu_lidar_yaw_fusion = sensor_fusion.imu_lidar_yaw_fusion:main',
            'mpc_planner = sensor_fusion.mpc_planner:main',
            'hybrid_astar_planner = sensor_fusion.hybrid_astar_planner:main',
            'frenet_path_smoother = sensor_fusion.frenet_path_smoother:main',
            'dwa_local_planner = sensor_fusion.dwa_local_planner:main',
            'test_navigation = sensor_fusion.test.test_navigation:main',
            'test_realtime_astar = sensor_fusion.test.test_realtime_astar:main',
            'test_hybrid_astar = sensor_fusion.test.test_hybrid_astar:main',
            'test_astar_config = sensor_fusion.test.test_astar_config:main',
            'test_map_data_format = sensor_fusion.test.test_map_data_format:main',
            'test_goal_pose_publisher = sensor_fusion.test_goal_pose_publisher:main',
            'current_pose_publisher = sensor_fusion.test.current_pose_publisher:main',
            'cluster_to_nav2_map_converter = sensor_fusion.cluster_to_nav2_map_converter:main',
            'lidar_vehicle_filter_node = sensor_fusion.lidar_vehicle_filter_node:main',
            'path_to_trajectory_converter = sensor_fusion.path_to_trajectory_converter:main',
            'trajectory_visualizer = sensor_fusion.trajectory_visualizer:main',
            'test_path_publisher = sensor_fusion.test_path_publisher:main',
            'trajectory_controller = sensor_fusion.trajectory_controller:main',
            'mpc_trajectory_controller = sensor_fusion.mpc_trajectory_controller:main',
        ],
    },
)
